angular.module('CardMatch.factory', [])
.factory('CardFactory', function() {
  return [{
    id: 'card1',
    name: 'stairs',
    url: 'img/illusion1.jpeg'
  }, {
    id: 'card2',
    name: 'stairs',
    url: 'img/illusion1.jpeg'
  }, {
    id: 'card3',
    name: 'dice',
    url: 'img/illusion2.jpg'
  }, {
    id: 'card4',
    name: 'dice',
    url: 'img/illusion2.jpg'
  }, {
    id: 'card5',
    name: 'doorZip',
    url: 'img/illusion9.jpg'
  }, {
    id: 'card6',
    name: 'doorZip',
    url: 'img/illusion9.jpg'
  }, {
    id: 'card7',
    name: 'windmillSoldier',
    url: 'img/illusion3.jpeg'
  }, {
    id: 'card8',
    name: 'windmillSoldier',
    url: 'img/illusion3.jpeg'
  }, {
    id: 'card9',
    name: 'spinningWheels',
    url: 'img/illusion4.jpg'
  }, {
    id: 'card10',
    name: 'spinningWheels',
    url: 'img/illusion4.jpg'
  }, {
    id: 'card11',
    name: 'riderMan',
    url: 'img/illusion10.jpg'
  }, {
    id: 'card12',
    name: 'riderMan',
    url: 'img/illusion10.jpg'
  }, {
    id: 'card13',
    name: 'oldYoung',
    url: 'img/illusion5.jpg'
  }, {
    id: 'card14',
    name: 'oldYoung',
    url: 'img/illusion5.jpg'
  }, {
    id: 'card15',
    name: 'groupFace',
    url: 'img/illusion7.jpg'
  }, {
    id: 'card16',
    name: 'groupFace',
    url: 'img/illusion7.jpg'
  }, {
    id: 'card17',
    name: 'birdFish',
    url: 'img/illusion6.jpg'
  }, {
    id: 'card18',
    name: 'birdFish',
    url: 'img/illusion6.jpg'
  }, {
    id: 'card19',
    name: 'tableHead',
    url: 'img/illusion8.jpg'
  }, {
    id: 'card20',
    name: 'tableHead',
    url: 'img/illusion8.jpg'
  }];
});
